#!/bin/bash

chmod 755 application.py
zip -g function.zip application.py

# Update the .zip file with the lambda and all its dependencies from the cmd line
aws lambda update-function-code --function-name Tides --zip-file fileb://function.zip
